pipeline {
    agent any
    
    stages {
        stage('Clean')
        {
             steps {
                    sh 'mvn -f passport/pom.xml clean'
                
            }
        }
        stage('Compile')
        {
             steps {
                    sh 'mvn -f passport/pom.xml compile'
                
            }
        }
       
        stage('Package') {
            steps {
                    sh 'mvn -f passport/pom.xml package'
                
            }
        }
        stage('Test') { 
            steps {
                sh 'mvn -f passport/pom.xml test' 
            }
            
        }
    }
}
