pipeline {
    agent any
    tools{
        maven 'Maven'
        jdk 'JDK'
    }
    
    stages {
        
        stage('Clean')
        {
             steps {
                    bat 'mvn -f passport/pom.xml clean'
                
            }
        }
       
        stage('Package') {
            steps {
                    bat 'mvn -f passport/pom.xml package'
                
            }
        }
       
        stage( 'SonarQube analysis'){
            steps {
              withSonarQubeEnv('localpassport') {
                bat 'mvn -f passport/pom.xml sonar:sonar'
              }
            }
        }
        stage('collect artifact'){
     steps{
     archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false
     }
     }
     stage('deploy to artifactory')
     {
     steps{
     
     rtUpload (
    serverId: 'ARTIFACTORY_SERVER',
    spec: '''{
          "files": [
            {
              "pattern": "target/*.jar",
              "target": "arti-maven-dev-loc"
            }
         ]
    }''',
 
  
    buildName: 'holyFrog',
    buildNumber: '42'
)
     }}
    }
}
