pipeline {
    agent any
    tools{
        maven 'Maven'
        jdk 'JDK'
    }
    
    stages {
        stage('Clean')
        {
             steps {
                    bat 'mvn -f passport/pom.xml clean'
                
            }
        }
       
        stage('Package') {
            steps {
                    bat 'mvn -f passport/pom.xml package'
                
            }
        }
       
        stage( 'SonarQube analysis'){
            steps {
              withSonarQubeEnv('localsonar') {
                bat 'mvn -f passport/pom.xml sonar:sonar'
              }
            }
        }
    }
}
